package com.rocketpartners.onboarding.possystem.event;

/**
 * Enum for POS event types.
 */
public enum PosEventType {
    POS_BOOTUP,
    POS_SHUTDOWN,
    REQUEST_START_TRANSACTION,
    TRANSACTION_STARTED,
    REQUEST_VOID_TRANSACTION,
    TRANSACTION_VOIDED,
    REQUEST_COMPLETE_TRANSACTION,
    TRANSACTION_COMPLETED,
    REQUEST_RESET_POS,
    POS_RESET,
    REQUEST_ADD_ITEM,
    ADD_ITEM,
    REQUEST_VOID_ITEM,
    VOID_ITEM,
    REQUEST_PAY_WITH_CASH,
    INSERT_CASH,
    CASH_INSERTED,
    REQUEST_PAY_WITH_CARD,
    ENTER_CARD_NUMBER,
    CARD_NUMBER_ENTERED,
    ENTER_CARD_PIN,
    CARD_PIN_ENTERED,
    REQUEST_CANCEL_PAYMENT,
    CANCEL_PAYMENT,
}
